name: AutoDownloader
on:
  workflow_dispatch
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Aria2 Install
      run: sudo apt install -y transmission-cli
    - name: Inject Rclone&Aria2 config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF

    - name: Rtorrent_Downloading_File
      run: |
        mkdir downloads
        rtorrent -o dht.mode.set=disable,throttle.global_down.max_rate.set_kb=10240,dht.mode.set=off,directory.default.set=~/downloads "${{ secrets.URL}}"
        



    - name: Rclone Synchronizing file
      run: |
        rclone copy downloads ${{ secrets.D}} -P --bwlimit 10M


